In [35]:
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PowerTransformer, StandardScaler, OneHotEncoder
from imblearn.over_sampling import SMOTE


# load the data
df = pd.read_csv('../data/customer_churn_data.csv',index_col=0)

In [36]:
# separate the features and target variable
X = df.drop('Attrition_Flag', axis=1)
y = df['Attrition_Flag']

    # get the list of numerical features
num_cols = X.select_dtypes(include=['int64', 'float64']).columns.tolist()

    # normalize skewed features with PowerTransformer
pt = PowerTransformer()
X[num_cols] = pt.fit_transform(X[num_cols])

    # scale features with StandardScaler
scaler = StandardScaler()
X[num_cols] = scaler.fit_transform(X[num_cols])

In [37]:
# one hot encode categorical features
encoder = OneHotEncoder(handle_unknown='ignore')
X_cat = encoder.fit_transform(X.select_dtypes(include=['object']))

In [44]:
X.isna()

,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio
CLIENTNUM,,,,,,,,,,,,,,,,,,,
768805383,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
818770008,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
713982108,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
769911858,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
709106358,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
772366833,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
710638233,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
716506083,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
717406983,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
714337233,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [34]:
X = pd.join([pd.DataFrame(X[num_cols]), pd.DataFrame(X_cat.toarray())], axis=1)

AttributeError: module 'pandas' has no attribute 'join'